replicaCount: 2
image:
  tag: "sha-b922ee409a4636bdbbecf3691305988037fd12cb"
  pullPolicy: "Always"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.phuocnguyen.dpdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: restaurant-backend-tls
      hosts:
        - api.phuocnguyen.dpdns.org
env:
  dbHost: "restaurant-db.production.svc.cluster.local"
  dbPort: "1433"
  dbUser: "sa"
  dbName: "RESTAURANT_DB"
  dbEncrypt: "false"
  dbTrustCert: "true"
  keycloakServerUrl: "http://keycloak.keycloak.svc.cluster.local"
  keycloakRealm: "master"
  keycloakClientId: "restaurant-app"
  frontendUrl: "https://staff.phuocnguyen.dpdns.org"
# Trỏ tới production credentials secret đã mã hóa qua Sealed Secrets
existingSecret: "backend-prod-secret"
dbPasswordKey: "postgres-password"
keycloakSecretKey: "keycloak-client-secret"
