replicaCount: 2
image:
  tag: "sha-d7988689dc5c153769625fbd4b9eae4afa09a6de"
  pullPolicy: "Always"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: phuocnguyen.dpdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: restaurant-frontend-tls
      hosts:
        - phuocnguyen.dpdns.org
env:
  apiUrl: "https://api.phuocnguyen.dpdns.org"
