replicaCount: 2
image:
  tag: "sha-462ecf78c0f43a62cd1c71084891fdc91204550d"
  pullPolicy: "Always"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: staff.phuocnguyen.dpdns.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: restaurant-frontend-tls
      hosts:
        - staff.phuocnguyen.dpdns.org
env:
  apiUrl: "https://api.phuocnguyen.dpdns.org"
