---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-admin-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgA7x8X/VXvNpkxEYkQNtQ96VvrzhUTMWXWLbauDAjkZE0ryucnbuNNzXOsgj6y/Mx9IUolEwwLFMEVHqW0lkZ2z7tgS4ZFIBAwJcLo+tdyREA0n+9hOuME2W1ZUIZfQsyK6+xP5Jb6OULhKGalE32htJGf8uimIv67iYm5GvA1UF0jv08ais+QEE14cWguaKwcrb4FzTZZBEx1m8xGP8z6ENF3OH7Qh7az0AJbbOcUgyMLtByyly/Q8LYG2djJAxNjmFGTREWkoWA1unI2waerYwCYvlg6DoWdZuu1i7hiV08V8QbgnG67jNr/MTdjgzrE5hbjCt6ChndZNDl3v2qDQVdu88eFcBrostsdIadcTMwD2yjlrjPPV3Xq9n/8fNRjc6MfmIsnU6svOQv5uIRjmMThul0sG/RFPviPL8+rtRoZr3bkAKOtKrZDlcLhubT700j4qx6xscQd0f/rlg+/xmfbI28w0G1GdU1ZwCJlqwmsCGIo3D1YdOYtU+CSoP3DihwFfKYk4E7D4Y3LamTpmjhSky2PSZ913p3euFeQzRSAv0vSi9Huuk8ILrsM7dazR1kwCT0r3K0xa7wVwu9W7yFWXb650f8kjMIEgmHTV4yrZqST1mjWkn4515VGVNlL6HcQ7DGyHGBu2WhW4yc5cnky5o9QLMCLa4EXWTBkC5WhrEcZ77thl9PT644XihUQ7lpKavvZ55v6mpbHNLDajYBEjYAoHECMPaNQ=
  template:
    metadata:
      name: argocd-admin-secret
      namespace: argocd
