---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-secret
  namespace: production
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCZ91G+8+0ZqC2/QwrSvjgY3//N1oQmEnp8LA56QTKLPfKFnJnuiNr+eh3VEvT/JLdotyQOURmzP5qo9+6o0X1ti8wCeT72gh+BCsJTzl21Dpo1cudXaqrwtO2Kcj9xhWR1lnOyHj0aG3T7BkPXa7SE8PmX7wOJjLemkYr6MIv46pb6o2YnEF1XB0XEteQkvbXkq5tkdzNMi+9wLsfclaclFoi2lD+iLeXGg9lCo/fVzGpCDWauYhUz+uSmUtvKSLgWjfZGZ1ntmRSESYAXXLkHwlF81kj46uppkunhekM5osKlgntn0xLG2krp/1gG9lJOicjodS8D+kQRVkawubH8jy3SKqoybP7sEY6D47bWWRgb3fATmL+vZMUq1KkZbxOwEDJg+LlqJcj3Tr48JjW3PdWv+STgOzvFvgX0Q2IuEurqy/PkrUy6Ob9ekJtiIv7i47TiDgU1k5BaYVihtSLau5NfJy2TcOaVHUY04xLitmBWzX2Xwp0mY4t7gGYT0Z4/Grgg6iap2+HARXCgY7XDHGy8jJ6FQMbHVzsEKWSBfV6bQ+pfHJtuyjLMs3lXNeqoJVJpwLYnmEQNbPQKmpfDClMSCuw/ZQwdYZ0vRCH22qDcE9FNwgeSaDgB9GFAeXzTLgji7aNPJlRiZW9hXRfJCe28nOnmHepr/SZtXwauQvUNhAgUU0dbykvVGEEuUA8Fk6E91oJTzz82fLaNC6v2WVD7vanKdK94DVECIA5Iryfw7xih9CbDsA/iUi57f5X6pnClUk34ojG5i0CFmRph94UalY3uxoMyHgNwjW6qJEq67YFgu6rlEZYuZIaj83n+4yyEEMQ3C/q5vimIHMI6fLdrikUU+fvJFamxNK0RA2DIgv4hlJQqzXp21IYdkA0mGBbEczF5yD5sHza6jOWznjiw0bF7z7mWf4QJTlKH0DKdByYCmrYC
  template:
    metadata:
      name: cloudflared-secret
      namespace: production
