---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAtxp449jYHKxDpctM7vslywn2L7hzCT/5o6Y2hdfASVM5jty/0F21EAJ2Ke5lPZ2n7PeT/G2iH4N8XsnVYPFZMain/QTRqFNXAM76TBpLTDYpZQ5J3LixLmoXs1gOsKME2aN7OuRiYCSFVcaLmiBquKe59rJNaTlYzuqR0/khA+nrWEZyOUm3WUBk7Hq0x0ikRb5N2evQJnJNBbnmOWAaL1giKOIg+M5onoL1sbsPxxjg5BSi8G8Gran2Ij9v20pGyN7tC1mJRXz7tSzZ/sBeEX+2HaA593+nPRfbIB70ciE87D9VhJLKicsEM5SBm/5Jhvn3oxDQiGBO9QptpKLsyZgnsWm+/T4wxHhYyUyrd1OqcfARM8aYqWVVt1ptytrhRg1WSlAkDPyayZl+5P0p1QHwyNb7mAShzS0qpATDbjVQ2wK/8CHSxQHETqq5jFlTDIRxaoZ7AR088BYgEcphGlnl6ly1k7blv0dIL7+UHEUHbR5ZjISqW8AOGIutO0wljVyYchWh+VDFSuiwCwAMrKytGa9DRd+1GKJmHUki4JjNFo/CXeVlwg1kmhysASZd17Z4utstA8h/KJNZ4me9yMJvXMKDTFcYG75Y4PrWYJDbJXpbHrSvSBqVf8hXYMjJKLKKpaaHr5MxagutQ5hr/4frZO2EL0mPQm8fdkdsUKaVdnxIv2wJfHHDzbem9Ii1uNnyrS78SglU904pattqIwIy89a6/ORUZrDVX/Zw=
    admin-user: AgBLHhGtbe13YY24gGAF9DNF3r/G78XBlyeIqURtncpxgir26RmzfEmvYWjHuZDBZmMcQ9APsZQ/LSVZk6y/hpmk/fUgqbiR4Ha5xcUYt/jY776B/M9G2p1/yG0q0z/UomYfKcInlLqLcjxqHYVh5ZdLHMJ5avCZBTtZLIzp1RQopVpEMdhkPhyB8pLxKF8bClc3d4Q7AfIDLf9aMH2YhBTfpcAvHbidL3yqtlD8qpxpn45GTJXRfBsoRE4I+UZjj2myCknL/znkiBNPT7CO7nzv2lXIJUZPfx6Lmqv+5mA8sf+lWCwRt8Lmrya5zxdmz4kzvryZm9+lCp7vLwGgSFzxc/U5NMdLSYW8UxP5/EvbZR8cYvZYs28RpVJouN5K0IYUkYR21JsbaiVi7MlnfTEtjm6KpV4BxuBJqNmzkLn7p37Fx4VQJr2EBfDhep0KosOnrJbNpSdLzG59ejNH8sI2K7O0Xc9DeudsyHUq1xB/kXQlBkSJq/JPsVkv32ViUncBt7paPAz9z5l6/unEMH+t2x51a83foyQVyb1GJRZ47HnPKD3xHi9iXsBuEmm4cSTpZgAEnuXMdedWcRb6JdvA3Ebxp1r+KSmNxmWXRlifWFPSGYj4o7HkAhMpYpHPUz9XEzB9+dNJX6ai2Hn0wGNiLr1aeli/YM/ERxRwxQE+18IY062yMxLmvLxMVpOvAU5yNejC/w==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
