---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin-secret
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgAEAqR1NnZOUzuQdMjjw0m+/Yl8rRmbVAxyLsbduQJ124wp48udHQtqHSoeZ1g06coJQzJ77T2fyN7ZXOEEkntiCmqgOye66XfTdxrwLlZ/dyBVviGtS5OT10+YsZ+aXg76jl/8oAdqZ5anHo9sgNsa4Pcbt5l6oLEhgUwnDkexP6amt5wBAyr8ZULrqNT8wQpbqvhkCVj76VGDD1GHDi0XdNlJ+4enEggbJUzVwbx/fBsceRFRgMNMc6cY7IKqq7CJztzUnWFxj+ngu2uRa6UO30GRC2NWLpPBvM5t7gw2hdzhBxsgfFpL+BVtlLyeAf0QPHRIOWuXOS85hDxyxuSIjX8s55AimYEoMXrAodpBYswMlALnjXyNLFw6rJN86fNKJmTF3PmoLl1GVEMg1tfYb+JOCQiKTaTqXd8CpdZBp5yyXh1xD/cMocCGO09TfMHD/I6sSPI4R3IMX61djGZuHkY2OJrmbqInXfzyobMtgBpB4IndZ4FLWeIDjSRR4ZIkycYV5VUogc8WRDpU0CFIP27JpVdk0oxx10q4zhjVZQzRwe3LryEiJWHer9OzqI06uubYUkizsBXvZztTvCk+smkpTGLm6s0NHQ9M71e3+ByVQu5zbhRa5TXlaT8K0uLywTElrO+s/Qp+vJyuiMKcMsaBmhw9Fr7/Mkh6HPVrv2KUWiVI6co12aI9D8QceCzMvBC0KbH63OTYyb37J6982epUUdvYsuygIYQJtkiB
    admin-user: AgB3xJLMR+qqn8ics6LdHaiku/Mo671zZvIdDPEazlv3zndOJ0Ntoh+AtCICgOX72c8YmJrZRUG8z7K17cK01Vrat3jlTmA541NfB7MXSRGlrCM9Vq0x9lY3TawRjwGNGPxYlq8NYWJrqNF1lYFGOVYLCsnT/Z1qUUwqR5g56Uach2pko9Lc4AyI1mV+f8RUlV3EHz++IwRYqxxd40nU2VvA5rwVQ6H3dwGhByXJG9N8gQz8iLTTHu38yu9g0puztVGDFg9BEQdFK3KSlx7So4alEpFDgLBDHjBCL6gsF0FcL84wUs6Y20Iv2S2mfqtXnremniGJStNs+zfOKADV+39v4je3Idu/ruKghkbXFii4pGbatY1nbLJ2W46BkuQqR5naBaW7njanNH5JEjdNf1XNGPt1F5yosoLmIuZGRRKLGyY7txWOMq9Y9MmumiqrjovmbLjIxhbcfE2+TgFav0x8IyMgYMnRhLa/XwW5UyEteVk+vFPrFRLCSRHdV6Tb/qHU5f5PKetP5sBYrZFchwplnjvGOMmf/Q4yP2EathGXVMg2NafTrgsAbTGwM6FVwc9z/T1d6eoELjbCjfAFtv5jY5PP0bcN64rW1ZG9llGqD6AiBN049QxS7rTrtCJwnngTGKPKCwxfiu9BDH6rOcA/Vua7JIM3fDDssT/5NxT5TDmvhj5UJQfjDKS8e70WzJSQ+O+R6A==
  template:
    metadata:
      name: keycloak-admin-secret
      namespace: keycloak
