---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mssql-secret
  namespace: production
spec:
  template:
    metadata:
      name: mssql-secret
      namespace: production
    type: Opaque
  encryptedData:
    SA_PASSWORD: AgA8X... # Managed via SealedSecrets controller or kubeseal
