---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-realm-import
  namespace: keycloak
spec:
  template:
    metadata:
      name: keycloak-realm-import
      namespace: keycloak
    type: Opaque
  encryptedData:
    realm-import.json: AgA34... # Encrypted realm import data managed via SealedSecrets controller or kubeseal
