apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure-project
  namespace: argocd
spec:
  description: Project containing infrastructure stack for Restaurant Management System
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
