apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-import
  namespace: keycloak
data:
  realm-import.json: |
    {
      "realm": "master",
      "enabled": true,
      "roles": {
        "realm": [
          {
            "name": "1",
            "description": "Admin"
          },
          {
            "name": "2",
            "description": "manager"
          },
          {
            "name": "3",
            "description": "staff"
          },
          {
            "name": "4",
            "description": "kitchenstaff"
          }
        ]
      },
      "clients": [
        {
          "clientId": "restaurant-app",
          "enabled": true,
          "publicClient": false,
          "secret": "K00hfckOeKM41NCdo75fSUTjmWR4akou",
          "directAccessGrantsEnabled": true,
          "standardFlowEnabled": true,
          "serviceAccountsEnabled": true,
          "redirectUris": [
            "*"
          ],
          "webOrigins": [
            "*"
          ]
        }
      ]
    }
