# Kube-Prometheus-Stack Helm Values
grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password
  service:
    type: NodePort

  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
      jsonData:
        maxLines: 1000

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
