# ArgoCD Helm Values Configuration
global:
  domain: argocd.minikube.local

server:
  service:
    type: NodePort
  config:
    repositories: |
      - url: https://github.com/phuocnguyennam/quan_li_nha_hang.git
        type: git
        name: main-repo
    url: http://argocd.minikube.local
  livenessProbe:
    timeoutSeconds: 15
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 5
  readinessProbe:
    timeoutSeconds: 15
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 5

repoServer:
  livenessProbe:
    timeoutSeconds: 15
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 5
  readinessProbe:
    timeoutSeconds: 15
    initialDelaySeconds: 30
    periodSeconds: 15
    failureThreshold: 5

configs:
  cm:
    url: http://argocd.minikube.local
    admin.enabled: "true"
